# Generated by Django 4.2.1 on 2023-10-31 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conectaplusapp', '0003_alter_message_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='estados',
            field=models.CharField(choices=[('PE', 'Pernambuco'), ('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro ')], default='PE', max_length=2),
        ),
        migrations.AddField(
            model_name='projeto',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conectaplusapp.voluntario'),
        ),
    ]
