# Generated by Django 4.2.1 on 2023-10-31 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conectaplusapp', '0004_projeto_ativo_projeto_estados_projeto_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='estados',
            field=models.CharField(choices=[('PE', 'Pernambuco'), ('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro')], default='PE', max_length=2),
        ),
    ]
