# Generated by Django 4.2.6 on 2023-10-31 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conectaplusapp', '0005_projeto_cidade_alter_projeto_estados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
